### ISSUE TITLE
Seems to not be working

### ISSUE THREAD

**Issue by Katzenwerfer** [emielsteegh/vscode-never-nest#1]
Found your extension earlier and tried to test it in C++ file.

So far, it doesn't seem to work at all, though it doesn't spit out any errors I could find.

**Comment by Katzenwerfer** [comment]
I'm open to helping you fix it, but I'm extremely inexperienced with anything JS, so at best I can try and log some stuff on my side

**Comment by Katzenwerfer** [comment]
I might be stupid. It didn't occur to me that the extension is only enabled by default for specific languages. Since the description page on the marketplace says that it's enabled for all languages, I would have thought that was the case, but it doesn't seem to be.

**Comment by emielsteegh** [comment]
Kind of ironic the extension wasnt enabled for C/Cpp by default considering the Torvalds quote in the readme is about C, haha. 

Anyways, thanks for reporting it and excuse my very late response, I addressed it in the 1.4.0 release. I orginally set it only to some languages because I disliked how red my HTML files were turning. But, it is now enabled by default for all languages, with some new shiny exclusions.

I hope you are enjoying the extension!
